alias es='eza -F --group-directories-first'
alias el='eza -lF --group-directories-first'
alias elg='eza -lF --group-directories-first --git'
alias esp='eza -F --group-directories-first -d $PWD/*'
alias bat='bat --wrap never'
alias glowp='PAGER=bat glow --pager'
alias zj='zellij'
alias cldt='claude --disallowedTools "Bash,Grep,Glob"'