"""FIXED harness — owns data loading + the metric. NEVER edit during experiments.

Editing this file (the metric, the data subset, the fixed constants) silently
breaks comparability with every prior result. The training code (train.py) owns
the model class, weight init, optimizer, scheduler, and the training loop; this
harness owns everything that must stay constant so variants are comparable and
the metric is uncheatable.
"""

# ============================================================================
#  DO NOT EDIT THIS FILE DURING EXPERIMENTS.
#  It owns data loading + the metric so every variant is comparable & uncheatable.
#  To change what is fixed, start a NEW autoresearch branch and edit deliberately.
# ============================================================================

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Callable, Protocol

from dynamics import Recorder, write_dynamics_csv

if TYPE_CHECKING:
    import lightning as L
    import torch
    from torch import nn
    from torch.utils.data import DataLoader


# --- FIXED constants ----------------------------------------------------------
SEED: int = 42
DEFAULT_BUDGET_MIN: float = 5.0

# TODO(autoresearch): data source, train/val split, fixed fast-iteration subset,
# metric key. These define what is held constant across every experiment.

# `kind` identifies which validation loader/metric is being scored. The project
# may narrow this to a Literal (e.g. Literal["train-val", "val-val"]).
ValSplits = str
PRIMARY_VAL_KIND: ValSplits = "val"  # TODO(autoresearch): your primary val kind


# --- spec / context types -----------------------------------------------------


class ScoreFn(Protocol):
    """Stateful score callable handed to train_fn.

    Calling `score(kind, model)` runs `spec.eval_forward(model, batch)` over
    `val_loaders[kind]`, computes the metric, returns it, and updates the
    harness-owned running best for `kind`.
    """

    def __call__(self, kind: str, model: nn.Module) -> float: ...
    def best(self, kind: str) -> float: ...


@dataclass
class TrainContext:
    fabric: L.Fabric
    model: nn.Module  # fabric.setup'd
    # The project config from build_spec()'s ExperimentSpec. This is where
    # train_fn reads its hyperparameters (lr, weight decay, etc.).
    cfg: dict[str, Any]
    train_loader: DataLoader[Any]
    val_loaders: dict[str, DataLoader[Any]]
    budget_sec: float
    score: ScoreFn
    recorder: Recorder


@dataclass
class TrainResult:
    num_steps: int
    training_seconds: float


EvalForward = Callable[["nn.Module", dict[str, Any]], "torch.Tensor"]
TrainFn = Callable[[TrainContext], TrainResult]


@dataclass(frozen=True)
class ExperimentSpec:
    """The contract returned by `train.build_spec()`.

    The harness builds dataloaders from `cfg` + `max_items`, computes
    `num_params_M` + `depth` by introspecting `model`, runs `train_fn` with a
    `TrainContext`, and reads `score.best(kind)` after.

    `cfg` is a free-form project config dict (feature flags, architecture
    knobs, anything train.py wants to thread through to the data builders).
    """

    cfg: dict[str, Any]
    max_items: int
    model: nn.Module
    train_fn: TrainFn
    eval_forward: EvalForward


# --- summary / score helpers --------------------------------------------------


def emit_summary(metrics: dict[str, Any]) -> None:
    """Print the summary block to stdout.

    Format is load-bearing: the launcher greps ``^<primary_metric>:`` and reads
    field 2. The primary metric MUST be the FIRST printed line so the grep
    contract picks the right value.
    """
    print("---")
    # TODO(autoresearch): rename val_metric to your primary metric. Apply the
    # SAME rename in all coupled spots or you'll KeyError on first run:
    # (1) this key, (2) the "val_metric" key in run_experiment's return dict,
    # (3) the `val_metric = ...` local in run_experiment that feeds that key.
    print(f"val_metric:       {metrics['val_metric']:.6f}")
    print(f"training_seconds: {metrics['training_seconds']:.1f}")
    print(f"total_seconds:    {metrics['total_seconds']:.1f}")
    print(f"peak_vram_mb:     {metrics['peak_vram_mb']:.1f}")
    print(f"num_steps:        {metrics['num_steps']}")
    print(f"num_params_M:     {metrics['num_params_M']:.1f}")
    print(f"depth:            {metrics['depth']}")


def update_best(current_best: float, candidate: float) -> float:
    """Take max(current_best, candidate) with NaN safety."""
    cb_nan = math.isnan(current_best)
    cand_nan = math.isnan(candidate)
    if cb_nan and cand_nan:
        return math.nan
    if cb_nan:
        return candidate
    if cand_nan:
        return current_best
    return max(current_best, candidate)


def _introspect_depth(model: nn.Module) -> int:
    """Best-effort depth introspection. train.py can override by setting
    `model.n_layers = N` for a clean self-report."""
    n = getattr(model, "n_layers", None)
    if isinstance(n, int):
        return n
    try:
        from torch import nn

        return sum(
            1 for m in model.modules() if isinstance(m, nn.TransformerEncoderLayer)
        )
    except Exception:  # noqa: BLE001
        return 0


# --- data builders ------------------------------------------------------------


def build_train_dataloader(cfg: dict[str, Any]) -> DataLoader[Any]:
    # TODO(autoresearch): build from your data source; return the fixed subset.
    raise NotImplementedError(
        "TODO(autoresearch): build the fixed train dataloader from your data source"
    )


def build_val_dataloaders(cfg: dict[str, Any]) -> dict[str, DataLoader[Any]]:
    # TODO(autoresearch): build from your data source; return the fixed subset.
    # The returned dict's keys MUST include PRIMARY_VAL_KIND, else
    # score.best(PRIMARY_VAL_KIND) in run_experiment raises KeyError.
    raise NotImplementedError(
        "TODO(autoresearch): build the fixed val dataloaders from your data source"
    )


# --- harness internals --------------------------------------------------------


def _compute_metric_stub() -> float:
    # TODO(autoresearch): DELETE this stub entirely and compute the metric INLINE
    # in `_make_score_fn` (where `loader`, `preds`, and `batch` are in scope).
    # This stub exists only so the skeleton compiles; it is not meant to be filled in.
    raise NotImplementedError(
        "TODO(autoresearch): compute your primary validation metric"
    )


def _make_score_fn(
    fabric: L.Fabric,
    val_loaders: dict[str, DataLoader[Any]],
    eval_forward: EvalForward,
    recorder: Recorder,
) -> ScoreFn:
    import torch

    # `fabric` is threaded through for the copier's real metric impl (e.g.
    # `fabric.device` when moving targets onto the accelerator); not dead.
    best: dict[str, float] = {kind: math.nan for kind in val_loaders}

    class _Score:
        def __call__(self, kind: str, model: nn.Module) -> float:
            loader = val_loaders[kind]
            was_training = model.training
            model.eval()
            # TODO(autoresearch): plug your metric here (the ONE place the
            # metric lives). Iterate `loader`, run `eval_forward(model, batch)`,
            # read the target from `batch`, and reduce to the scalar `val`.
            with torch.no_grad():
                for batch in loader:
                    preds = eval_forward(model, batch)
                    del preds  # replace with metric accumulation
            val = _compute_metric_stub()
            best[kind] = update_best(best[kind], val)
            recorder.log(f"val_metric/{kind}", val, step=recorder.last_step())
            if was_training:
                model.train()
            return val

        def best(self, kind: str) -> float:
            return best[kind]

    return _Score()


def run_experiment(
    spec: ExperimentSpec, *, budget_min: float = DEFAULT_BUDGET_MIN
) -> dict[str, Any]:
    """Run one experiment within `budget_min` wall-clock minutes."""
    import os
    import time

    import lightning as L
    import torch

    t_total_start = time.monotonic()
    crashed = False
    crash_reason = ""
    result = TrainResult(num_steps=0, training_seconds=0.0)

    try:
        num_params_m = sum(p.numel() for p in spec.model.parameters()) / 1e6
    except Exception:  # noqa: BLE001
        num_params_m = 0.0
    depth = _introspect_depth(spec.model)

    recorder = Recorder()
    score_fn: ScoreFn | None = None
    try:
        torch.set_float32_matmul_precision("medium")
        fabric = L.Fabric(accelerator="gpu", devices=1, precision="bf16-mixed")
        fabric.launch()

        seed = int(os.environ.get("AUTORES_SEED", SEED))
        fabric.seed_everything(seed)

        train_loader = build_train_dataloader(spec.cfg)
        val_loaders = build_val_dataloaders(spec.cfg)

        model = fabric.setup(spec.model)
        train_loader = fabric.setup_dataloaders(train_loader)
        val_loaders = {
            kind: fabric.setup_dataloaders(loader)
            for kind, loader in val_loaders.items()
        }

        score_fn = _make_score_fn(
            fabric, val_loaders, spec.eval_forward, recorder
        )

        ctx = TrainContext(
            fabric=fabric,
            model=model,
            cfg=spec.cfg,
            train_loader=train_loader,
            val_loaders=val_loaders,
            budget_sec=budget_min * 60.0,
            score=score_fn,
            recorder=recorder,
        )
        result = spec.train_fn(ctx)

    except torch.cuda.OutOfMemoryError as exc:  # type: ignore[attr-defined]
        crashed, crash_reason = True, f"OOM: {exc}"
    except Exception as exc:  # noqa: BLE001
        crashed, crash_reason = True, f"{type(exc).__name__}: {exc}"
    finally:
        write_dynamics_csv(
            "run_dynamics.csv",
            series=recorder.snapshot(),
            meta={
                "num_steps": str(result.num_steps),
                "crashed": str(crashed).lower(),
                "budget_sec": f"{budget_min * 60.0:.0f}",
            },
        )

    t_total_elapsed = time.monotonic() - t_total_start
    peak_vram_mb = (
        torch.cuda.max_memory_allocated() / 1024**2
        if torch.cuda.is_available()
        else 0.0
    )

    best_primary = (
        score_fn.best(PRIMARY_VAL_KIND) if score_fn is not None else math.nan
    )
    val_metric = (
        best_primary if not crashed and not math.isnan(best_primary) else 0.0
    )

    if crashed:
        import sys

        print(f"[autores] crashed: {crash_reason}", file=sys.stderr)

    return {
        "val_metric": val_metric,
        "training_seconds": result.training_seconds,
        "total_seconds": t_total_elapsed,
        "peak_vram_mb": peak_vram_mb,
        "num_steps": result.num_steps,
        "num_params_M": num_params_m,
        "depth": depth,
        "crashed": crashed,
    }
